(specifications->manifest
 '(
   "emacs-config-minimal"
   "emacs-config-base"
   "emacs-config-docs"
   "emacs-config-peter-public"
   "emacs-config-peter-personal"
   "emacs-config-peter-email"
   ))
