#+TITLE: Desktop Environment

#+PROPERTY: header-args :mkdirp yes
#+PROPERTY: header-args:sh   :tangle-mode (identity #o555)
#+PROPERTY: header-args:conf :tangle-mode (identity #o555)

This file contains configuration for my overall desktop environment.  My workflow is driven by Emacs but there are still a number of applications, tools, themes, and fonts that I must install to have a complete desktop experience.

* Channels

#+begin_src scheme :tangle .config/guix/channels.scm
(use-modules (guix ci))

(list (channel-with-substitutes-available
       %default-guix-channel
       "https://ci.guix.gnu.org"))

;; This repository contains setup and management instructions for a Guix North American Build Farm.

;; Using Substitutes from cuirass.genenetwork.org
;; On Guix System
;; If you're using Guix System, you can use the cuirass.genenetwork.org substitute server completing the following:

;; Add https://cuirass.genenetwork.org to the list of substitute servers (using the substitute-urls field of guix-configuration passed to the guix-daemon service).
;; Adjust guix-daemon ACLs to include the following public key (using the authorized-keys field of guix-configuration passed to the guix-daemon service).

;; (public-key
;;  (ecc
;;   (curve Ed25519)
;;   (q #9578AD6CDB23BA51F9C4185D5D5A32A7EEB47ACDD55F1CCB8CEE4E0570FBF961#)
;;   )
;; )
;; In the future, we hope to work with Guix maintainers to include this substitute server as one of the provided Guix System defaults.

;; On Foreign Distributions
;; When using Guix on a foreign distribution, you'll need to do the following to enable substitutes from cuirass.genenetwork.org:

;; Add the public key (provided above) for cuirass.genenetwork.org to the guix-daemon ACLs.

;; curl -L   -o /tmp/cuirass.genenetwork.org.pub   'https://git.genenetwork.org/guix-north-america/plain/.pubkeys/guix/cuirass.genenetwork.org.pub'
;; sudo guix archive --authorize < cuirass.genenetwork.org.pub
;; Add the substitute url using the --substitute-urls option to guix-daemon. Assuming your foreign distribution uses systemd, this can be done using the following.

;; sudo systemctl edit --full guix-daemon
;; If you want to just use ci.guix.gnu.org, or cuirass.genenetwork.org for that matter, you'll need to adjust the substitute URLs configuration for the guix-daemon to just refer to the substitute servers you want to use. Once edited and saved, restart the guix daemon.
;; ExecStart=/gnu/store/.../bin/guix-daemon --build-users-group=guixbuild \
;;   --substitute-urls='https://cuirass.genenetwork.org https://ci.guix.gnu.org https://bordeaux.guix.gnu.org'

;; sudo systemctl daemon-reload
;; sudo systemctl restart guix-daemon.service
;; Reference
;; Intial Setup Instructions
;; Details the initial setup of a genenetwork.org sponsored, single node build farm.
;; Administration of cuirass.genenetwork.org
;; details maintenance and administration of cuirass.genenetwork.org
#+end_src

* System Packages

*Guix Packages*

#+begin_src scheme :noweb-ref packages :noweb-sep ""
"nss-certs"
"glibc-locales"
"git"
"stow"
"myrepos"
"gparted"
"graphviz"
"password-store"
"gnupg"
"paperkey"
"qrencode"
"curl"
"xkeysnail"
"flatpak"
"nfs-utils"
"cifs-utils"
"exa"
"bat"
"guile-hall"
#+end_src

* Fonts and Themes

I use [[https://github.com/derat/xsettingsd][xsettingsd]] as a minimal settings daemon for Xorg applications.  It replaces similar daemons from desktop environments like GNOME and XFCE and enables me to use a simple configuration file like the following:

*.config/xsettingsd/xsettingsd.conf:*

#+begin_src conf :tangle .config/xsettingsd/xsettingsd.conf :noweb yes
Net/ThemeName "Matcha-dark-azul"
Net/IconThemeName "Papirus-Dark"
Gtk/DecorationLayout "menu:minimize,maximize,close"
Gtk/FontName "Cantarell 11"
Gtk/MonospaceFontName "Fira Mono 10"
Gtk/CursorThemeName "Adwaita"
Xft/Antialias 1
Xft/Hinting 0
Xft/HintStyle "hintnone"
#+end_src

I also have to do an extra step to make sure Emacs can find the font path from the "desktop" profile.

*.config/fontconfig/fonts.conf:*

#+begin_src xml :tangle .config/fontconfig/fonts.conf
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <dir>~/.dotfiles/fonts</dir>
  <dir>~/.guix-extra-profiles/desktop/desktop/share/fonts</dir>
  <alias>
    <family>Apple Color Emoji</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
</fontconfig>
#+end_src

*Guix Packages*

#+begin_src scheme :noweb-ref packages :noweb-sep ""
;; Settin gs Manager
"xsettingsd"

;; GTK Themes
"arc-icon-theme"
"matcha-theme"
"hicolor-icon-theme"
"adwaita-icon-theme"
"gnome-backgrounds"
"papirus-icon-theme"
"breeze-icons"

;; Fonts
"font-fira-code"
"font-jetbrains-mono"
"font-iosevka"
"font-iosevka-aile"
"font-abattis-cantarell"
"font-dejavu"
"font-google-noto"
"font-gnu-freefont"
"font-liberation"
"font-awesome"
"font-google-material-design-icons"
"font-ghostscript"
#+end_src

* Flatpak

#+begin_src sh
flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
#+end_src

* Desktop Profile

The =desktop.scm= manifest holds the list of packages that I use to configure my desktop environment.  The package names are pulled from the relevant sections titled *Guix Packages* in this file (=Desktop.org=).

*.config/guix/manifests/desktop.scm:*

#+begin_src scheme :tangle .config/guix/manifests/desktop.scm :noweb yes
(specifications->manifest
 '(
   <<packages>>
   ))
#+end_src
