#!/usr/bin/env bash
echo "mr status: ~/Repositories"
cd ~/Repositories
mr -m status 2>/dev/null

echo "git status: ~/.dotfiles"
cd ~/.dotfiles
git status -s

echo "git status: ~/.password-store"
cd ~/.password-store
git status -s

echo "git status: ~/guix"
cd ~/guix
git status -s
