#!/bin/sh
echo "mr status: ~/Repositories"
cd ~/Repositories
mr -m status 2>/dev/null | sed '/^$/d'

echo "git status: ~/.dotfiles"
cd ~/.dotfiles
git status -s

echo "git status: ~/.password-store"
cd ~/.password-store
git status -s
