#!/usr/bin/env bash
sleep 1
echo "git pull: ~/.dotfiles"
cd ~/.dotfiles
git pull

sleep 1
echo "git pull: ~/.password-store"
cd ~/.password-store
git pull

echo "git pull: ~/Repositories"
cd ~/Repositories
mr run sleep 1 && git pull 2>/dev/null
