#!/bin/sh
mbsync -a
mu init --maildir=$HOME/Email/ --my-address=peterpolidoro@gmail.com --my-address=io@mechatronicmagic.io --my-address=polidorop@janelia.hhmi.org --my-address=peter@polidoro.io
mu index
