#!/bin/sh
# Navigate to the directory of this script (generally ~/.dotfiles/.bin)
cd $(dirname $(readlink -f $0))
./upgrade-guix-system
./upgrade-guix-user
./pull-repositories
./sync-email
./upgrade-guix-repository
