[General]
__userfile__=true
panels=panel1, panel2

[desktopswitch]
alignment=Left
rows=1
showOnlyActive=false
type=desktopswitch

[fancymenu2]
alignment=Left
ownIcon=true
type=fancymenu

[kbindicator2]
alignment=Right
type=kbindicator

[mount2]
alignment=Right
type=mount

[panel1]
alignment=-1
animation-duration=0
background-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=0
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
hidable=false
hide-on-overlap=false
iconSize=22
lineCount=1
lockPanel=false
opacity=100
panelSize=32
plugins=showdesktop, taskbar, desktopswitch
position=Bottom
reserve-space=true
show-delay=0
visible-margin=true
width=100
width-percent=true

[showdesktop]
alignment=Right
type=showdesktop

[spacer]
alignment=Left
expandable=true
spaceType=invisible
type=spacer

[statusnotifier2]
alignment=Left
type=statusnotifier

[sysstat]
alignment=Right
type=sysstat

[taskbar]
alignment=Left
autoRotate=true
buttonHeight=100
buttonStyle=IconText
buttonWidth=200
closeOnMiddleClick=true
excludedList=
groupingEnabled=false
iconByClass=false
raiseOnCurrentDesktop=true
showDesktopNum=0
showGroupOnHover=true
showOnlyCurrentScreenTasks=false
showOnlyMinimizedTasks=false
showOnlyOneDesktopTasks=true
type=taskbar
ungroupedNextToExisting=false
wheelDeltaThreshold=300
wheelEventsAction=0

[worldclock2]
alignment=Right
autoRotate=true
customFormat="'<b>'HH:mm:ss'</b><br/><font size=\"-2\">'ddd, d MMM yyyy'<br/>'TT'</font>'"
dateFormatType=custom
dateLongNames=false
datePadDay=false
datePosition=after
dateShowDoW=true
dateShowYear=false
defaultTimeZone=
formatType=custom-timeonly
showDate=true
showTimezone=false
showTooltip=false
showWeekNumber=true
timeAMPM=true
timePadHour=false
timeShowSeconds=false
timeZones\size=0
timezoneFormatType=iana
timezonePosition=below
type=worldclock
useAdvancedManualFormat=false

[panel2]
alignment=0
animation-duration=0
background-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=0
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
hidable=false
hide-on-overlap=false
iconSize=22
lineCount=1
lockPanel=false
opacity=100
panelSize=32
plugins=fancymenu2, quicklaunch, spacer, kbindicator2, sysstat, statusnotifier2, mount2, worldclock2
position=Top
reserve-space=true
show-delay=0
visible-margin=true
width=100
width-percent=true

[quicklaunch]
alignment=Left
apps\1\desktop=kitty.desktop
apps\2\desktop=firefox-esr.desktop
apps\3\desktop=google-chrome.desktop
apps\4\desktop=lximage-qt.desktop
apps\5\desktop=thunar.desktop
apps\size=5
type=quicklaunch
