[Behavior]
ConfirmDelete=true
ConfirmTrash=false
SingleClick=false
UseTrash=true

[Desktop]
DesktopShortcuts=Home, Trash, Computer, Network
Wallpaper=/usr/share/lxqt/themes/debian/wallpaper.svg
WallpaperMode=zoom
WallpaperRandomize=false

[FolderView]
Mode=icon
ShowHidden=false
SortCaseSensitive=false
SortColumn=name
SortFolderFirst=true
SortOrder=ascending

[System]
Archiver=xarchiver
Terminal=kitty

[Thumbnail]
ShowThumbnails=true
ThumbnailLocalFilesOnly=true

[Window]
AlwaysShowTabs=true
PathBarButtons=true
ReopenLastTabs=false
ShowMenuBar=true
ShowTabClose=true
SidePaneMode=places
SidePaneVisible=true
SwitchToNewTab=false
